name: quiz_flutter
description: My Tech Quiz


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.0
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  google_sign_in: ^6.0.2
  flip_card: ^0.7.0
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.4.0
  password_strength: ^0.2.0
  skeletons: ^0.0.3
  numberpicker: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


flutter:  
  uses-material-design: true
  fonts:
    - family: Heming
      fonts: 
        - asset: assets/fonts/Heming.ttf
  assets:
    - assets/images/