name: quiz_flutter
description: My Tech Quiz


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  google_sign_in: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


flutter:  
  uses-material-design: true
  fonts:
    - family: Sono
      fonts: 
        - asset: assets/fonts/Sono.ttf
  assets:
    - assets/images/